- hosts: servers
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Deploy Application
      shell: docker-compose up -d
      args:
        chdir: /home/ubuntu/devops-project

